// Read the MCP skill files under ../skills/mcp/ (generated from
// skills/mcp-server.{see,watch}.md by skills/generate-skills.py) and emit
// src/prompts.generated.ts so the server can import name / description /
// body as strings. The same SKILL.md files double as installable skills.
//
// Runs in the build chain before tsc, so the generated .ts file exists
// when type checking runs.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Paths are relative to this file (mcp-server/); the skills live one level up.
const SOURCES = [
  { exportName: 'PROMPT_SEE',   file: '../skills/mcp/see-what-i-see/SKILL.md' },
  { exportName: 'PROMPT_WATCH', file: '../skills/mcp/see-what-i-see-watch/SKILL.md' },
];

/**
 * Parse a markdown file with YAML frontmatter. We only need scalar `key: value`
 * pairs (no nesting, no lists) so a tiny parser suffices and we avoid taking
 * a js-yaml dep just for this.
 */
function parseFrontmatter(text, filePath) {
  if (!text.startsWith('---\n')) {
    throw new Error(`${filePath}: missing leading '---' frontmatter delimiter`);
  }
  const closeIdx = text.indexOf('\n---\n', 4);
  if (closeIdx === -1) {
    throw new Error(`${filePath}: missing closing '---' frontmatter delimiter`);
  }
  const meta = {};
  const headerLines = text.slice(4, closeIdx).split('\n');
  for (const line of headerLines) {
    if (!line.trim() || line.startsWith('#')) continue;
    const eq = line.indexOf(':');
    if (eq === -1) {
      throw new Error(`${filePath}: malformed frontmatter line: ${line}`);
    }
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    // Strip matched surrounding quotes if present.
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    meta[key] = value;
  }
  if (!meta.name) throw new Error(`${filePath}: frontmatter is missing 'name'`);
  if (!meta.description) throw new Error(`${filePath}: frontmatter is missing 'description'`);
  // Body starts after the closing delimiter; trim leading newline.
  const body = text.slice(closeIdx + 5).replace(/^\n+/, '').replace(/\n+$/, '\n');
  return { name: meta.name, description: meta.description, body };
}

const lines = [
  '// Generated by build-prompts.mjs from ../skills/mcp/*/SKILL.md. Do not edit.',
  '// Those SKILL.md files are themselves generated by',
  '// skills/generate-skills.py from skills/mcp-server.{see,watch}.md.',
  '',
  'export interface PromptDefinition {',
  '  name: string;',
  '  description: string;',
  '  body: string;',
  '}',
  '',
];

for (const { exportName, file } of SOURCES) {
  const fullPath = resolve(__dirname, file);
  const text = readFileSync(fullPath, 'utf8');
  const parsed = parseFrontmatter(text, file);
  lines.push(
    `export const ${exportName}: PromptDefinition = ${JSON.stringify(parsed, null, 2)};`,
    '',
  );
}

const outPath = resolve(__dirname, 'src/prompts.generated.ts');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n'));
process.stdout.write(`Wrote ${outPath}\n`);
